package com.english.pronunciation

/**
 * First batch of thematic word blocks. More categories will be added
 * incrementally to reach the full planned set.
 */
object CategoryBank {
    val categories = listOf(
        Category(
            id = "toys",
            title = "Игрушки",
            icon = "🧸",
            words = listOf(
                Word("toy", "tɔɪ", "игрушка", "🎁"),
                Word("doll", "dɒl", "кукла", "🪆"),
                Word("teddy bear", "ˈtedi beər", "плюшевый мишка", "🧸"),
                Word("ball", "bɔːl", "мяч", "⚽"),
                Word("puzzle", "ˈpʌzl", "пазл", "🧩"),
                Word("blocks", "blɒks", "кубики", "🧱"),
                Word("robot", "ˈroʊbɒt", "робот", "🤖"),
                Word("kite", "kaɪt", "воздушный змей", "🪁"),
                Word("drum", "drʌm", "барабан", "🥁"),
                Word("balloon", "bəˈluːn", "воздушный шарик", "🎈"),
                Word("yo-yo", "ˈjoʊjoʊ", "йо-йо", "🪀"),
                Word("dice", "daɪs", "игральный кубик", "🎲"),
                Word("crayon", "ˈkreɪɒn", "восковой мелок", "🖍️"),
                Word("sticker", "ˈstɪkər", "наклейка", "🏷️"),
                Word("bubble", "ˈbʌbl", "мыльный пузырь", "🫧"),
                Word("slide", "slaɪd", "горка", "🛝"),
                Word("sandbox", "ˈsændbɒks", "песочница", "🏖️"),
                Word("skateboard", "ˈskeɪtbɔːrd", "скейтборд", "🛹"),
                Word("jump rope", "dʒʌmp roʊp", "скакалка", "🪢"),
                Word("game", "ɡeɪm", "игра", "🎮")
            )
        ),
        Category(
            id = "city",
            title = "Город",
            icon = "🌃",
            words = listOf(
                Word("street", "striːt", "улица", "🛣️"),
                Word("building", "ˈbɪldɪŋ", "здание", "🏢"),
                Word("bridge", "brɪdʒ", "мост", "🌉"),
                Word("park", "pɑːrk", "парк", "🏞️"),
                Word("shop", "ʃɒp", "магазин", "🏪"),
                Word("bus", "bʌs", "автобус", "🚌"),
                Word("train", "treɪn", "поезд", "🚆"),
                Word("traffic light", "ˈtræfɪk laɪt", "светофор", "🚦"),
                Word("bank", "bæŋk", "банк", "🏦"),
                Word("church", "tʃɜːrtʃ", "церковь", "⛪"),
                Word("restaurant", "ˈrestərɒnt", "ресторан", "🍽️"),
                Word("hotel", "hoʊˈtel", "отель", "🏨"),
                Word("museum", "mjuˈziːəm", "музей", "🏛️"),
                Word("library", "ˈlaɪbreri", "библиотека", "📚"),
                Word("hospital", "ˈhɒspɪtl", "больница", "🏥"),
                Word("school", "skuːl", "школа", "🏫"),
                Word("station", "ˈsteɪʃn", "вокзал", "🚉"),
                Word("square", "skwer", "площадь", "🏙️"),
                Word("tower", "ˈtaʊər", "башня", "🗼"),
                Word("city", "ˈsɪti", "город", "🌆")
            )
        ),
        Category(
            id = "family",
            title = "Семья",
            icon = "👪",
            words = listOf(
                Word("mother", "ˈmʌðər", "мама", "👩🏻"),
                Word("father", "ˈfɑːðər", "папа", "👨🏻"),
                Word("sister", "ˈsɪstər", "сестра", "👧🏻"),
                Word("brother", "ˈbrʌðər", "брат", "👦🏻"),
                Word("grandmother", "ˈɡrænmʌðər", "бабушка", "👵🏻"),
                Word("grandfather", "ˈɡrænfɑːðər", "дедушка", "👴🏻"),
                Word("daughter", "ˈdɔːtər", "дочь", "👧🏻"),
                Word("son", "sʌn", "сын", "👦🏻"),
                Word("aunt", "ænt", "тётя", "👩🏻"),
                Word("uncle", "ˈʌŋkl", "дядя", "👨🏻"),
                Word("cousin", "ˈkʌzn", "двоюродный брат/сестра", "🧑🏻"),
                Word("wife", "waɪf", "жена", "👰"),
                Word("husband", "ˈhʌzbənd", "муж", "🤵🏻"),
                Word("baby", "ˈbeɪbi", "младенец", "👶🏻"),
                Word("parents", "ˈperənts", "родители", "👨‍👩‍👧"),
                Word("family", "ˈfæməli", "семья", "👨‍👩‍👧‍👦"),
                Word("friend", "frend", "друг", "🧑🏻‍🤝‍🧑🏻"),
                Word("neighbor", "ˈneɪbər", "сосед", "🏠"),
                Word("twins", "twɪnz", "близнецы", "👯"),
                Word("relative", "ˈrelətɪv", "родственник", "🧑🏻‍🦰")
            )
        ),
        Category(
            id = "food",
            title = "Еда",
            icon = "🍽️",
            words = listOf(
                Word("bread", "bred", "хлеб", "🍞"),
                Word("cheese", "tʃiːz", "сыр", "🧀"),
                Word("meat", "miːt", "мясо", "🥩"),
                Word("soup", "suːp", "суп", "🍲"),
                Word("salad", "ˈsæləd", "салат", "🥗"),
                Word("sandwich", "ˈsænwɪdʒ", "бутерброд", "🥪"),
                Word("pizza", "ˈpiːtsə", "пицца", "🍕"),
                Word("rice", "raɪs", "рис", "🍚"),
                Word("pasta", "ˈpɑːstə", "паста", "🍝"),
                Word("egg", "eɡ", "яйцо", "🥚"),
                Word("butter", "ˈbʌtər", "масло", "🧈"),
                Word("honey", "ˈhʌni", "мёд", "🍯"),
                Word("sugar", "ˈʃʊɡər", "сахар", "🍬"),
                Word("salt", "sɔːlt", "соль", "🧂"),
                Word("pepper", "ˈpepər", "перец", "🫑"),
                Word("sauce", "sɔːs", "соус", "🥫"),
                Word("cake", "keɪk", "торт", "🎂"),
                Word("cookie", "ˈkʊki", "печенье", "🍪"),
                Word("breakfast", "ˈbrekfəst", "завтрак", "🍳"),
                Word("dinner", "ˈdɪnər", "ужин", "🍽️")
            )
        ),
        Category(
            id = "animals",
            title = "Животные",
            icon = "🐾",
            words = listOf(
                Word("dog", "dɒɡ", "собака", "🐶"),
                Word("cat", "kæt", "кошка", "🐱"),
                Word("horse", "hɔːrs", "лошадь", "🐴"),
                Word("cow", "kaʊ", "корова", "🐄"),
                Word("sheep", "ʃiːp", "овца", "🐑"),
                Word("pig", "pɪɡ", "свинья", "🐷"),
                Word("chicken", "ˈtʃɪkɪn", "курица", "🐔"),
                Word("duck", "dʌk", "утка", "🦆"),
                Word("fish", "fɪʃ", "рыба", "🐟"),
                Word("lion", "ˈlaɪən", "лев", "🦁"),
                Word("tiger", "ˈtaɪɡər", "тигр", "🐯"),
                Word("elephant", "ˈelɪfənt", "слон", "🐘"),
                Word("monkey", "ˈmʌŋki", "обезьяна", "🐒"),
                Word("bear", "ber", "медведь", "🐻"),
                Word("fox", "fɒks", "лиса", "🦊"),
                Word("deer", "dɪr", "олень", "🦌"),
                Word("mouse", "maʊs", "мышь", "🐭"),
                Word("frog", "frɒɡ", "лягушка", "🐸"),
                Word("snake", "sneɪk", "змея", "🐍"),
                Word("turtle", "ˈtɜːrtl", "черепаха", "🐢")
            )
        ),
        Category(
            id = "body",
            title = "Тело человека",
            icon = "🧍🏻",
            words = listOf(
                Word("head", "hed", "голова", "🙂"),
                Word("hand", "hænd", "рука (кисть)", "✋🏻"),
                Word("leg", "leɡ", "нога", "🦵🏻"),
                Word("arm", "ɑːrm", "рука", "🦾"),
                Word("eye", "aɪ", "глаз", "👁️"),
                Word("ear", "ɪr", "ухо", "👂🏻"),
                Word("nose", "noʊz", "нос", "👃🏻"),
                Word("mouth", "maʊθ", "рот", "👄"),
                Word("hair", "her", "волосы", "💇"),
                Word("tooth", "tuːθ", "зуб", "🦷"),
                Word("finger", "ˈfɪŋɡər", "палец", "👆🏻"),
                Word("neck", "nek", "шея", "🦒"),
                Word("shoulder", "ˈʃoʊldər", "плечо", "🤷"),
                Word("back", "bæk", "спина", "🧍🏻"),
                Word("knee", "niː", "колено", "🦵🏻"),
                Word("foot", "fʊt", "ступня", "🦶🏻"),
                Word("chest", "tʃest", "грудь", "🫁"),
                Word("heart", "hɑːrt", "сердце", "❤️"),
                Word("skin", "skɪn", "кожа", "🧴"),
                Word("elbow", "ˈelboʊ", "локоть", "💪")
            )
        ),
        Category(
            id = "clothes",
            title = "Одежда",
            icon = "👕",
            words = listOf(
                Word("shirt", "ʃɜːrt", "рубашка", "👕"),
                Word("dress", "dres", "платье", "👗"),
                Word("skirt", "skɜːrt", "юбка", "👗"),
                Word("jacket", "ˈdʒækɪt", "куртка", "🧥"),
                Word("coat", "koʊt", "пальто", "🧥"),
                Word("shoes", "ʃuːz", "туфли", "👞"),
                Word("socks", "sɒks", "носки", "🧦"),
                Word("hat", "hæt", "шляпа", "🎩"),
                Word("gloves", "ɡlʌvz", "перчатки", "🧤"),
                Word("scarf", "skɑːrf", "шарф", "🧣"),
                Word("jeans", "dʒiːnz", "джинсы", "👖"),
                Word("sweater", "ˈswetər", "свитер", "🧶"),
                Word("belt", "belt", "ремень", "➰"),
                Word("tie", "taɪ", "галстук", "👔"),
                Word("boots", "buːts", "ботинки", "🥾"),
                Word("pajamas", "pəˈdʒɑːməz", "пижама", "🛌"),
                Word("suit", "suːt", "костюм", "🤵🏻"),
                Word("shorts", "ʃɔːrts", "шорты", "🩳"),
                Word("underwear", "ˈʌndərwer", "нижнее бельё", "🩲"),
                Word("uniform", "ˈjuːnɪfɔːrm", "форма", "🎽")
            )
        ),
        Category(
            id = "house",
            title = "Дом",
            icon = "🏠",
            words = listOf(
                Word("kitchen", "ˈkɪtʃɪn", "кухня", "🍳"),
                Word("bedroom", "ˈbedruːm", "спальня", "🛏️"),
                Word("bathroom", "ˈbæθruːm", "ванная", "🚿"),
                Word("living room", "ˈlɪvɪŋ ruːm", "гостиная", "🛋️"),
                Word("door", "dɔːr", "дверь", "🚪"),
                Word("window", "ˈwɪndoʊ", "окно", "🪟"),
                Word("roof", "ruːf", "крыша", "🏠"),
                Word("wall", "wɔːl", "стена", "🧱"),
                Word("floor", "flɔːr", "пол", "🪵"),
                Word("ceiling", "ˈsiːlɪŋ", "потолок", "⬜"),
                Word("garden", "ˈɡɑːrdn", "сад", "🌻"),
                Word("garage", "ɡəˈrɑːʒ", "гараж", "🚗"),
                Word("stairs", "sterz", "лестница", "🪜"),
                Word("balcony", "ˈbælkəni", "балкон", "🏢"),
                Word("fence", "fens", "забор", "🚧"),
                Word("chimney", "ˈtʃɪmni", "дымоход", "🏭"),
                Word("key", "kiː", "ключ", "🔑"),
                Word("lamp", "læmp", "лампа", "💡"),
                Word("mirror", "ˈmɪrər", "зеркало", "🪞"),
                Word("carpet", "ˈkɑːrpɪt", "ковёр", "🟥")
            )
        ),
        Category(
            id = "nature",
            title = "Природа",
            icon = "🌳",
            words = listOf(
                Word("tree", "triː", "дерево", "🌳"),
                Word("flower", "ˈflaʊər", "цветок", "🌸"),
                Word("grass", "ɡræs", "трава", "🌱"),
                Word("forest", "ˈfɒrɪst", "лес", "🌲"),
                Word("river", "ˈrɪvər", "река", "🏞️"),
                Word("lake", "leɪk", "озеро", "🏞️"),
                Word("mountain", "ˈmaʊntən", "гора", "⛰️"),
                Word("sea", "siː", "море", "🌊"),
                Word("sky", "skaɪ", "небо", "🌤️"),
                Word("sun", "sʌn", "солнце", "☀️"),
                Word("moon", "muːn", "луна", "🌙"),
                Word("star", "stɑːr", "звезда", "⭐"),
                Word("cloud", "klaʊd", "облако", "☁️"),
                Word("rain", "reɪn", "дождь", "🌧️"),
                Word("snow", "snoʊ", "снег", "❄️"),
                Word("wind", "wɪnd", "ветер", "💨"),
                Word("stone", "stoʊn", "камень", "🪨"),
                Word("sand", "sænd", "песок", "🏖️"),
                Word("ice", "aɪs", "лёд", "🧊"),
                Word("leaf", "liːf", "лист", "🍁")
            )
        ),
        Category(
            id = "transport",
            title = "Транспорт",
            icon = "🚗",
            words = listOf(
                Word("car", "kɑːr", "машина", "🚗"),
                Word("bus", "bʌs", "автобус", "🚌"),
                Word("train", "treɪn", "поезд", "🚆"),
                Word("plane", "pleɪn", "самолёт", "✈️"),
                Word("ship", "ʃɪp", "корабль", "🚢"),
                Word("bicycle", "ˈbaɪsɪkl", "велосипед", "🚲"),
                Word("motorcycle", "ˈmoʊtərsaɪkl", "мотоцикл", "🏍️"),
                Word("taxi", "ˈtæksi", "такси", "🚕"),
                Word("subway", "ˈsʌbweɪ", "метро", "🚇"),
                Word("truck", "trʌk", "грузовик", "🚚"),
                Word("boat", "boʊt", "лодка", "⛵"),
                Word("helicopter", "ˈhelɪkɒptər", "вертолёт", "🚁"),
                Word("tram", "træm", "трамвай", "🚊"),
                Word("scooter", "ˈskuːtər", "самокат", "🛴"),
                Word("wheel", "wiːl", "колесо", "🛞"),
                Word("engine", "ˈendʒɪn", "двигатель", "⚙️"),
                Word("ticket", "ˈtɪkɪt", "билет", "🎫"),
                Word("driver", "ˈdraɪvər", "водитель", "🧑🏻‍✈️"),
                Word("airport", "ˈerpɔːrt", "аэропорт", "🛫"),
                Word("road", "roʊd", "дорога", "🛣️")
            )
        ),
        Category(
            id = "professions",
            title = "Профессии",
            icon = "🧑🏻‍💼",
            words = listOf(
                Word("teacher", "ˈtiːtʃər", "учитель", "🧑🏻‍🏫"),
                Word("doctor", "ˈdɒktər", "врач", "🧑🏻‍⚕️"),
                Word("nurse", "nɜːrs", "медсестра", "👩🏻‍⚕️"),
                Word("engineer", "ˌendʒɪˈnɪr", "инженер", "🧑🏻‍🔧"),
                Word("lawyer", "ˈlɔɪər", "юрист", "👨🏻‍⚖️"),
                Word("police officer", "pəˈliːs ˈɔːfɪsər", "полицейский", "👮🏻"),
                Word("firefighter", "ˈfaɪərfaɪtər", "пожарный", "👨🏻‍🚒"),
                Word("chef", "ʃef", "повар", "👨🏻‍🍳"),
                Word("waiter", "ˈweɪtər", "официант", "🧑🏻‍🍽️"),
                Word("pilot", "ˈpaɪlət", "пилот", "👨🏻‍✈️"),
                Word("farmer", "ˈfɑːrmər", "фермер", "👨🏻‍🌾"),
                Word("artist", "ˈɑːrtɪst", "художник", "🎨"),
                Word("musician", "mjuˈzɪʃn", "музыкант", "🎸"),
                Word("actor", "ˈæktər", "актёр", "🎭"),
                Word("scientist", "ˈsaɪəntɪst", "учёный", "🧑🏻‍🔬"),
                Word("dentist", "ˈdentɪst", "стоматолог", "🦷"),
                Word("plumber", "ˈplʌmər", "сантехник", "🔧"),
                Word("electrician", "ɪˌlekˈtrɪʃn", "электрик", "⚡"),
                Word("journalist", "ˈdʒɜːrnəlɪst", "журналист", "📰"),
                Word("hairdresser", "ˈherdresər", "парикмахер", "💇")
            )
        ),
        Category(
            id = "colors",
            title = "Цвета",
            icon = "🎨",
            words = listOf(
                Word("red", "red", "красный", "🔴"),
                Word("blue", "bluː", "синий", "🔵"),
                Word("green", "ɡriːn", "зелёный", "🟢"),
                Word("yellow", "ˈjeloʊ", "жёлтый", "🟡"),
                Word("orange", "ˈɔːrɪndʒ", "оранжевый", "🟠"),
                Word("purple", "ˈpɜːrpl", "фиолетовый", "🟣"),
                Word("pink", "pɪŋk", "розовый", "🩷"),
                Word("brown", "braʊn", "коричневый", "🟤"),
                Word("black", "blæk", "чёрный", "⚫"),
                Word("white", "waɪt", "белый", "⚪"),
                Word("gray", "ɡreɪ", "серый", "🩶"),
                Word("gold", "ɡoʊld", "золотой", "🥇"),
                Word("silver", "ˈsɪlvər", "серебряный", "🥈"),
                Word("turquoise", "ˈtɜːrkwɔɪz", "бирюзовый", "💎"),
                Word("beige", "beɪʒ", "бежевый", "🟨"),
                Word("navy", "ˈneɪvi", "тёмно-синий", "🔷"),
                Word("violet", "ˈvaɪələt", "фиалковый", "🟪"),
                Word("maroon", "məˈruːn", "тёмно-бордовый", "🟥"),
                Word("cyan", "ˈsaɪæn", "голубой", "🩵"),
                Word("lime", "laɪm", "лаймовый", "🟩")
            )
        ),
        Category(
            id = "numbers",
            title = "Числа",
            icon = "🧮",
            words = listOf(
                Word("one", "wʌn", "один", "1️⃣"),
                Word("two", "tuː", "два", "2️⃣"),
                Word("three", "θriː", "три", "3️⃣"),
                Word("four", "fɔːr", "четыре", "4️⃣"),
                Word("five", "faɪv", "пять", "5️⃣"),
                Word("six", "sɪks", "шесть", "6️⃣"),
                Word("seven", "ˈsevn", "семь", "7️⃣"),
                Word("eight", "eɪt", "восемь", "8️⃣"),
                Word("nine", "naɪn", "девять", "9️⃣"),
                Word("ten", "ten", "десять", "🔟"),
                Word("eleven", "ɪˈlevn", "одиннадцать", "🔢"),
                Word("twelve", "twelv", "двенадцать", "🔢"),
                Word("thirteen", "θɜːrˈtiːn", "тринадцать", "🔢"),
                Word("fourteen", "ˌfɔːrˈtiːn", "четырнадцать", "🔢"),
                Word("fifteen", "ˌfɪfˈtiːn", "пятнадцать", "🔢"),
                Word("sixteen", "ˌsɪksˈtiːn", "шестнадцать", "🔢"),
                Word("seventeen", "ˌsevnˈtiːn", "семнадцать", "🔢"),
                Word("eighteen", "ˌeɪˈtiːn", "восемнадцать", "🔢"),
                Word("nineteen", "ˌnaɪnˈtiːn", "девятнадцать", "🔢"),
                Word("twenty", "ˈtwenti", "двадцать", "🔢")
            )
        ),
        Category(
            id = "emotions",
            title = "Эмоции",
            icon = "😊",
            words = listOf(
                Word("happy", "ˈhæpi", "счастливый", "😊"),
                Word("sad", "sæd", "грустный", "😢"),
                Word("angry", "ˈæŋɡri", "злой", "😠"),
                Word("scared", "skerd", "испуганный", "😨"),
                Word("surprised", "sərˈpraɪzd", "удивлённый", "😲"),
                Word("tired", "ˈtaɪərd", "уставший", "😴"),
                Word("excited", "ɪkˈsaɪtɪd", "взволнованный", "🤩"),
                Word("nervous", "ˈnɜːrvəs", "нервный", "😬"),
                Word("proud", "praʊd", "гордый", "😌"),
                Word("bored", "bɔːrd", "скучающий", "😑"),
                Word("confused", "kənˈfjuːzd", "растерянный", "😕"),
                Word("calm", "kɑːm", "спокойный", "🧘🏻"),
                Word("worried", "ˈwɜːrid", "обеспокоенный", "😟"),
                Word("embarrassed", "ɪmˈbærəst", "смущённый", "😳"),
                Word("jealous", "ˈdʒeləs", "завистливый", "😒"),
                Word("grateful", "ˈɡreɪtfl", "благодарный", "🙏🏻"),
                Word("curious", "ˈkjʊriəs", "любопытный", "🤔"),
                Word("lonely", "ˈloʊnli", "одинокий", "😔"),
                Word("confident", "ˈkɒnfɪdənt", "уверенный", "😎"),
                Word("disappointed", "ˌdɪsəˈpɔɪntɪd", "разочарованный", "😞")
            )
        ),
        Category(
            id = "sport",
            title = "Спорт",
            icon = "⚽",
            words = listOf(
                Word("football", "ˈfʊtbɔːl", "футбол", "⚽"),
                Word("basketball", "ˈbæskɪtbɔːl", "баскетбол", "🏀"),
                Word("tennis", "ˈtenɪs", "теннис", "🎾"),
                Word("swimming", "ˈswɪmɪŋ", "плавание", "🏊🏻"),
                Word("running", "ˈrʌnɪŋ", "бег", "🏃🏻"),
                Word("cycling", "ˈsaɪklɪŋ", "велоспорт", "🚴"),
                Word("boxing", "ˈbɒksɪŋ", "бокс", "🥊"),
                Word("volleyball", "ˈvɒlibɔːl", "волейбол", "🏐"),
                Word("golf", "ɡɒlf", "гольф", "⛳"),
                Word("skiing", "ˈskiːɪŋ", "лыжи", "⛷️"),
                Word("skating", "ˈskeɪtɪŋ", "катание на коньках", "⛸️"),
                Word("gymnastics", "dʒɪmˈnæstɪks", "гимнастика", "🤸🏻"),
                Word("baseball", "ˈbeɪsbɔːl", "бейсбол", "⚾"),
                Word("hockey", "ˈhɒki", "хоккей", "🏒"),
                Word("rugby", "ˈrʌɡbi", "регби", "🏉"),
                Word("athlete", "ˈæθliːt", "спортсмен", "🏅"),
                Word("coach", "koʊtʃ", "тренер", "📣"),
                Word("stadium", "ˈsteɪdiəm", "стадион", "🏟️"),
                Word("medal", "ˈmedl", "медаль", "🥇"),
                Word("champion", "ˈtʃæmpiən", "чемпион", "🏆")
            )
        ),
        Category(
            id = "drinks",
            title = "Напитки",
            icon = "🥤",
            words = listOf(
                Word("tea", "tiː", "чай", "🍵"),
                Word("coffee", "ˈkɒfi", "кофе", "☕"),
                Word("juice", "dʒuːs", "сок", "🧃"),
                Word("milk", "mɪlk", "молоко", "🥛"),
                Word("water", "ˈwɔːtər", "вода", "💧"),
                Word("soda", "ˈsoʊdə", "газировка", "🥤"),
                Word("milkshake", "ˈmɪlkʃeɪk", "молочный коктейль", "🥤"),
                Word("yogurt", "ˈjoʊɡərt", "йогурт", "🥛"),
                Word("lemonade", "ˌleməˈneɪd", "лимонад", "🍋"),
                Word("smoothie", "ˈsmuːði", "смузи", "🍓"),
                Word("glass", "ɡlɑːs", "стакан", "🥛"),
                Word("cola", "ˈkoʊlə", "кола", "🧋"),
                Word("mug", "mʌɡ", "кружка", "🍵"),
                Word("iced tea", "aɪst tiː", "холодный чай", "🧊"),
                Word("hot chocolate", "hɒt ˈtʃɒklət", "какао", "🍫"),
                Word("thermos", "ˈθɜːrməs", "термос", "🧴"),
                Word("straw", "strɔː", "трубочка", "🥤"),
                Word("cup", "kʌp", "чашка", "☕"),
                Word("bottle", "ˈbɒtl", "бутылка", "🍼"),
                Word("kettle", "ˈketl", "чайник", "🫖")
            )
        ),
        Category(
            id = "furniture",
            title = "Мебель",
            icon = "🛋️",
            words = listOf(
                Word("table", "ˈteɪbl", "стол", "🟫"),
                Word("chair", "tʃer", "стул", "🪑"),
                Word("sofa", "ˈsoʊfə", "диван", "🛋️"),
                Word("bed", "bed", "кровать", "🛏️"),
                Word("wardrobe", "ˈwɔːrdroʊb", "шкаф", "🚪"),
                Word("shelf", "ʃelf", "полка", "📚"),
                Word("desk", "desk", "письменный стол", "🖥️"),
                Word("drawer", "drɔːr", "ящик", "🗄️"),
                Word("cupboard", "ˈkʌbərd", "буфет", "🗄️"),
                Word("bookcase", "ˈbʊkkeɪs", "книжный шкаф", "📚"),
                Word("stool", "stuːl", "табурет", "🪑"),
                Word("bench", "bentʃ", "скамья", "🪑"),
                Word("cabinet", "ˈkæbɪnət", "тумба", "🗄️"),
                Word("mattress", "ˈmætrəs", "матрас", "🛏️"),
                Word("pillow", "ˈpɪloʊ", "подушка", "🛌"),
                Word("blanket", "ˈblæŋkɪt", "одеяло", "🧣"),
                Word("curtain", "ˈkɜːrtn", "штора", "🪟"),
                Word("rug", "rʌɡ", "коврик", "🟥"),
                Word("armchair", "ˈɑːrmtʃer", "кресло", "🛋️"),
                Word("nightstand", "ˈnaɪtstænd", "тумбочка", "🕯️")
            )
        ),
        Category(
            id = "electronics",
            title = "Электроника",
            icon = "📱",
            words = listOf(
                Word("phone", "foʊn", "телефон", "📱"),
                Word("computer", "kəmˈpjuːtər", "компьютер", "🖥️"),
                Word("laptop", "ˈlæptɒp", "ноутбук", "💻"),
                Word("tablet", "ˈtæblət", "планшет", "📱"),
                Word("television", "ˈtelɪvɪʒn", "телевизор", "📺"),
                Word("camera", "ˈkæmərə", "фотоаппарат", "📷"),
                Word("headphones", "ˈhedfoʊnz", "наушники", "🎧"),
                Word("charger", "ˈtʃɑːrdʒər", "зарядка", "🔌"),
                Word("battery", "ˈbætəri", "батарейка", "🔋"),
                Word("keyboard", "ˈkiːbɔːrd", "клавиатура", "⌨️"),
                Word("mouse", "maʊs", "мышь (компьютерная)", "🖱️"),
                Word("monitor", "ˈmɒnɪtər", "монитор", "🖥️"),
                Word("printer", "ˈprɪntər", "принтер", "🖨️"),
                Word("router", "ˈruːtər", "роутер", "📡"),
                Word("speaker", "ˈspiːkər", "колонка", "🔊"),
                Word("microphone", "ˈmaɪkrəfoʊn", "микрофон", "🎤"),
                Word("remote control", "rɪˈmoʊt kənˈtroʊl", "пульт", "🎛️"),
                Word("console", "ˈkɒnsoʊl", "игровая консоль", "🎮"),
                Word("smartwatch", "ˈsmɑːrtwɒtʃ", "умные часы", "⌚"),
                Word("flash drive", "flæʃ draɪv", "флешка", "💾")
            )
        ),
        Category(
            id = "school",
            title = "Школа",
            icon = "🏫",
            words = listOf(
                Word("student", "ˈstuːdnt", "ученик", "🎓"),
                Word("classroom", "ˈklæsruːm", "класс", "🏫"),
                Word("book", "bʊk", "книга", "📖"),
                Word("pen", "pen", "ручка", "🖊️"),
                Word("pencil", "ˈpensl", "карандаш", "✏️"),
                Word("notebook", "ˈnoʊtbʊk", "тетрадь", "📓"),
                Word("backpack", "ˈbækpæk", "рюкзак", "🎒"),
                Word("blackboard", "ˈblækbɔːrd", "доска", "⬛"),
                Word("eraser", "ɪˈreɪsər", "ластик", "🧼"),
                Word("ruler", "ˈruːlər", "линейка", "📏"),
                Word("homework", "ˈhoʊmwɜːrk", "домашнее задание", "📝"),
                Word("exam", "ɪɡˈzæm", "экзамен", "📝"),
                Word("lesson", "ˈlesn", "урок", "📖"),
                Word("grade", "ɡreɪd", "оценка", "🅰️"),
                Word("calculator", "ˈkælkjəleɪtər", "калькулятор", "🧮"),
                Word("textbook", "ˈtekstbʊk", "учебник", "📕"),
                Word("schedule", "ˈskedʒuːl", "расписание", "🗓️"),
                Word("chalk", "tʃɔːk", "мел", "🖍️"),
                Word("principal", "ˈprɪnsəpl", "директор школы", "🧑🏻‍💼"),
                Word("recess", "ˈriːses", "перемена", "🔔")
            )
        ),
        Category(
            id = "shopping",
            title = "Магазин",
            icon = "🛒",
            words = listOf(
                Word("store", "stɔːr", "магазин", "🏬"),
                Word("cashier", "kæˈʃɪr", "кассир", "🧑🏻‍💼"),
                Word("price", "praɪs", "цена", "🏷️"),
                Word("discount", "ˈdɪskaʊnt", "скидка", "💸"),
                Word("receipt", "rɪˈsiːt", "чек", "🧾"),
                Word("basket", "ˈbæskɪt", "корзина", "🧺"),
                Word("cart", "kɑːrt", "тележка", "🛒"),
                Word("customer", "ˈkʌstəmər", "покупатель", "🙋🏻"),
                Word("wallet", "ˈwɒlɪt", "кошелёк", "👛"),
                Word("credit card", "ˈkredɪt kɑːrd", "банковская карта", "💳"),
                Word("cash", "kæʃ", "наличные", "💵"),
                Word("sale", "seɪl", "распродажа", "🏷️"),
                Word("queue", "kjuː", "очередь", "🚶"),
                Word("bag", "bæɡ", "сумка", "👜"),
                Word("size", "saɪz", "размер", "📏"),
                Word("fitting room", "ˈfɪtɪŋ ruːm", "примерочная", "🚪"),
                Word("brand", "brænd", "бренд", "™️"),
                Word("label", "ˈleɪbl", "этикетка", "🏷️"),
                Word("refund", "ˈriːfʌnd", "возврат денег", "💰"),
                Word("coupon", "ˈkuːpɒn", "купон", "🎟️")
            )
        ),
        Category(
            id = "weather",
            title = "Погода",
            icon = "🌦️",
            words = listOf(
                Word("sunny", "ˈsʌni", "солнечно", "☀️"),
                Word("rainy", "ˈreɪni", "дождливо", "🌧️"),
                Word("cloudy", "ˈklaʊdi", "облачно", "☁️"),
                Word("windy", "ˈwɪndi", "ветрено", "💨"),
                Word("snowy", "ˈsnoʊi", "снежно", "❄️"),
                Word("foggy", "ˈfɒɡi", "туманно", "🌫️"),
                Word("stormy", "ˈstɔːrmi", "штормовой", "⛈️"),
                Word("hot", "hɒt", "жарко", "🥵"),
                Word("cold", "koʊld", "холодно", "🥶"),
                Word("warm", "wɔːrm", "тепло", "🌤️"),
                Word("cool", "kuːl", "прохладно", "🍃"),
                Word("humid", "ˈhjuːmɪd", "влажно", "💦"),
                Word("freezing", "ˈfriːzɪŋ", "морозно", "🧊"),
                Word("thunder", "ˈθʌndər", "гром", "⚡"),
                Word("lightning", "ˈlaɪtnɪŋ", "молния", "🌩️"),
                Word("rainbow", "ˈreɪnboʊ", "радуга", "🌈"),
                Word("temperature", "ˈtemprətʃər", "температура", "🌡️"),
                Word("forecast", "ˈfɔːrkæst", "прогноз", "📅"),
                Word("degrees", "dɪˈɡriːz", "градусы", "🌡️"),
                Word("drizzle", "ˈdrɪzl", "морось", "🌦️")
            )
        ),
        Category(
            id = "space",
            title = "Космос",
            icon = "🚀",
            words = listOf(
                Word("planet", "ˈplænɪt", "планета", "🪐"),
                Word("galaxy", "ˈɡæləksi", "галактика", "🌌"),
                Word("astronaut", "ˈæstrənɔːt", "космонавт", "🧑🏻‍🚀"),
                Word("rocket", "ˈrɒkɪt", "ракета", "🚀"),
                Word("spaceship", "ˈspeɪsʃɪp", "космический корабль", "🛸"),
                Word("satellite", "ˈsætəlaɪt", "спутник", "🛰️"),
                Word("comet", "ˈkɒmɪt", "комета", "☄️"),
                Word("meteor", "ˈmiːtiər", "метеор", "☄️"),
                Word("universe", "ˈjuːnɪvɜːrs", "вселенная", "🌌"),
                Word("orbit", "ˈɔːrbɪt", "орбита", "🔄"),
                Word("alien", "ˈeɪliən", "инопланетянин", "👽"),
                Word("telescope", "ˈtelɪskoʊp", "телескоп", "🔭"),
                Word("mars", "mɑːrz", "марс", "🔴"),
                Word("earth", "ɜːrθ", "земля", "🌍"),
                Word("gravity", "ˈɡrævəti", "гравитация", "🌍"),
                Word("spacesuit", "ˈspeɪssuːt", "скафандр", "👨🏻‍🚀"),
                Word("asteroid", "ˈæstərɔɪd", "астероид", "🪨"),
                Word("sun", "sʌn", "солнце", "☀️"),
                Word("moon", "muːn", "луна", "🌙"),
                Word("star", "stɑːr", "звезда", "⭐")
            )
        ),
        Category(
            id = "holidays",
            title = "Праздники",
            icon = "🎉",
            words = listOf(
                Word("birthday", "ˈbɜːrθdeɪ", "день рождения", "🎂"),
                Word("christmas", "ˈkrɪsməs", "рождество", "🎄"),
                Word("holiday", "ˈhɒlədeɪ", "праздник", "🏖️"),
                Word("present", "ˈpreznt", "подарок", "🎁"),
                Word("candle", "ˈkændl", "свеча", "🕯️"),
                Word("fireworks", "ˈfaɪərwɜːrks", "фейерверк", "🎆"),
                Word("party", "ˈpɑːrti", "вечеринка", "🎉"),
                Word("celebration", "ˌselɪˈbreɪʃn", "празднование", "🥳"),
                Word("guest", "ɡest", "гость", "🙋🏻"),
                Word("invitation", "ˌɪnvɪˈteɪʃn", "приглашение", "💌"),
                Word("balloon", "bəˈluːn", "воздушный шар", "🎈"),
                Word("decoration", "ˌdekəˈreɪʃn", "украшение", "🎀"),
                Word("wish", "wɪʃ", "желание", "⭐"),
                Word("calendar", "ˈkælɪndər", "календарь", "📅"),
                Word("anniversary", "ˌænɪˈvɜːrsəri", "годовщина", "💍"),
                Word("wedding", "ˈwedɪŋ", "свадьба", "👰"),
                Word("parade", "pəˈreɪd", "парад", "🎊"),
                Word("cake", "keɪk", "торт", "🎂"),
                Word("easter", "ˈiːstər", "пасха", "🐰"),
                Word("new year", "njuː jɪr", "новый год", "🎊")
            )
        ),
        Category(
            id = "travel",
            title = "Путешествия",
            icon = "🧳",
            words = listOf(
                Word("passport", "ˈpæspɔːrt", "паспорт", "🛂"),
                Word("luggage", "ˈlʌɡɪdʒ", "багаж", "🧳"),
                Word("suitcase", "ˈsuːtkeɪs", "чемодан", "🧳"),
                Word("map", "mæp", "карта", "🗺️"),
                Word("tourist", "ˈtʊrɪst", "турист", "📸"),
                Word("journey", "ˈdʒɜːrni", "путешествие", "🚶"),
                Word("vacation", "veɪˈkeɪʃn", "отпуск", "🏖️"),
                Word("guide", "ɡaɪd", "гид", "🗺️"),
                Word("visa", "ˈviːzə", "виза", "📄"),
                Word("border", "ˈbɔːrdər", "граница", "🚧"),
                Word("currency", "ˈkʌrənsi", "валюта", "💱"),
                Word("souvenir", "ˌsuːvəˈnɪr", "сувенир", "🎁"),
                Word("adventure", "ədˈventʃər", "приключение", "🧭"),
                Word("destination", "ˌdestɪˈneɪʃn", "пункт назначения", "📍"),
                Word("itinerary", "aɪˈtɪnəreri", "маршрут", "🗒️"),
                Word("compass", "ˈkʌmpəs", "компас", "🧭"),
                Word("hotel", "hoʊˈtel", "отель", "🏨"),
                Word("ticket", "ˈtɪkɪt", "билет", "🎫"),
                Word("backpack", "ˈbækpæk", "рюкзак", "🎒"),
                Word("camera", "ˈkæmərə", "фотоаппарат", "📷")
            )
        ),
        Category(
            id = "health",
            title = "Здоровье",
            icon = "🏥",
            words = listOf(
                Word("medicine", "ˈmedsn", "лекарство", "💊"),
                Word("pill", "pɪl", "таблетка", "💊"),
                Word("toothbrush", "ˈtuːθbrʌʃ", "зубная щётка", "🪥"),
                Word("bandage", "ˈbændɪdʒ", "бинт", "🩹"),
                Word("thermometer", "θərˈmɒmɪtər", "градусник", "🌡️"),
                Word("fever", "ˈfiːvər", "жар", "🤒"),
                Word("headache", "ˈhedeɪk", "головная боль", "🤕"),
                Word("cough", "kɒf", "кашель", "😷"),
                Word("pain", "peɪn", "боль", "😖"),
                Word("injury", "ˈɪndʒəri", "травма", "🤕"),
                Word("wheelchair", "ˈwiːltʃer", "инвалидная коляска", "♿"),
                Word("ambulance", "ˈæmbjələns", "скорая помощь", "🚑"),
                Word("checkup", "ˈtʃekʌp", "осмотр", "🩺"),
                Word("vitamin", "ˈvaɪtəmɪn", "витамин", "💊"),
                Word("allergy", "ˈælərdʒi", "аллергия", "🤧"),
                Word("symptom", "ˈsɪmptəm", "симптом", "🩺"),
                Word("treatment", "ˈtriːtmənt", "лечение", "🏥"),
                Word("healthy", "ˈhelθi", "здоровый", "💪"),
                Word("recovery", "rɪˈkʌvəri", "выздоровление", "💪"),
                Word("hospital", "ˈhɒspɪtl", "больница", "🏥")
            )
        ),
        Category(
            id = "office",
            title = "Работа и офис",
            icon = "💼",
            words = listOf(
                Word("office", "ˈɔːfɪs", "офис", "🏢"),
                Word("meeting", "ˈmiːtɪŋ", "встреча", "🧑🏻‍🤝‍🧑🏻"),
                Word("email", "ˈiːmeɪl", "электронное письмо", "📧"),
                Word("deadline", "ˈdedlaɪn", "крайний срок", "⏰"),
                Word("project", "ˈprɒdʒekt", "проект", "📊"),
                Word("colleague", "ˈkɒliːɡ", "коллега", "🧑🏻‍💼"),
                Word("boss", "bɒs", "начальник", "👔"),
                Word("salary", "ˈsæləri", "зарплата", "💰"),
                Word("contract", "ˈkɒntrækt", "контракт", "📄"),
                Word("interview", "ˈɪntərvjuː", "собеседование", "🎙️"),
                Word("resume", "ˈrezəmeɪ", "резюме", "📄"),
                Word("presentation", "ˌprezenˈteɪʃn", "презентация", "📊"),
                Word("report", "rɪˈpɔːrt", "отчёт", "📈"),
                Word("teamwork", "ˈtiːmwɜːrk", "командная работа", "🤝"),
                Word("promotion", "prəˈmoʊʃn", "повышение", "📈"),
                Word("conference", "ˈkɒnfərəns", "конференция", "🎤"),
                Word("memo", "ˈmemoʊ", "служебная записка", "🗒️"),
                Word("printer", "ˈprɪntər", "принтер", "🖨️"),
                Word("computer", "kəmˈpjuːtər", "компьютер", "💻"),
                Word("schedule", "ˈskedʒuːl", "расписание", "🗓️")
            )
        ),
        Category(
            id = "kitchen",
            title = "Кухня",
            icon = "🍳",
            words = listOf(
                Word("fork", "fɔːrk", "вилка", "🍴"),
                Word("knife", "naɪf", "нож", "🔪"),
                Word("spoon", "spuːn", "ложка", "🥄"),
                Word("plate", "pleɪt", "тарелка", "🍽️"),
                Word("bowl", "boʊl", "миска", "🥣"),
                Word("pot", "pɒt", "кастрюля", "🍲"),
                Word("pan", "pæn", "сковорода", "🍳"),
                Word("oven", "ˈʌvn", "духовка", "🔥"),
                Word("fridge", "frɪdʒ", "холодильник", "🧊"),
                Word("microwave", "ˈmaɪkrəweɪv", "микроволновка", "📦"),
                Word("blender", "ˈblendər", "блендер", "🧃"),
                Word("toaster", "ˈtoʊstər", "тостер", "🍞"),
                Word("kettle", "ˈketl", "чайник", "🫖"),
                Word("cutting board", "ˈkʌtɪŋ bɔːrd", "разделочная доска", "🪵"),
                Word("napkin", "ˈnæpkɪn", "салфетка", "🧻"),
                Word("tray", "treɪ", "поднос", "🍱"),
                Word("jar", "dʒɑːr", "банка", "🫙"),
                Word("lid", "lɪd", "крышка", "🥫"),
                Word("spatula", "ˈspætʃələ", "лопатка", "🍳"),
                Word("whisk", "wɪsk", "венчик", "🥄")
            )
        ),
        Category(
            id = "verbs",
            title = "Глаголы действия",
            icon = "🏃🏻",
            words = listOf(
                Word("run", "rʌn", "бежать", "🏃🏻"),
                Word("jump", "dʒʌmp", "прыгать", "🤸🏻"),
                Word("walk", "wɔːk", "идти", "🚶"),
                Word("eat", "iːt", "есть", "🍽️"),
                Word("drink", "drɪŋk", "пить", "🥤"),
                Word("sleep", "sliːp", "спать", "😴"),
                Word("read", "riːd", "читать", "📖"),
                Word("write", "raɪt", "писать", "✍🏻"),
                Word("speak", "spiːk", "говорить", "🗣️"),
                Word("listen", "ˈlɪsn", "слушать", "👂🏻"),
                Word("watch", "wɒtʃ", "смотреть", "👀"),
                Word("play", "pleɪ", "играть", "🎮"),
                Word("work", "wɜːrk", "работать", "💼"),
                Word("study", "ˈstʌdi", "учиться", "📚"),
                Word("cook", "kʊk", "готовить", "🍳"),
                Word("swim", "swɪm", "плавать", "🏊🏻"),
                Word("dance", "dæns", "танцевать", "💃🏻"),
                Word("sing", "sɪŋ", "петь", "🎤"),
                Word("draw", "drɔː", "рисовать", "🎨"),
                Word("laugh", "læf", "смеяться", "😂")
            )
        ),
        Category(
            id = "adjectives",
            title = "Определения",
            icon = "📏",
            words = listOf(
                Word("big", "bɪɡ", "большой", "🐘"),
                Word("small", "smɔːl", "маленький", "🐭"),
                Word("tall", "tɔːl", "высокий", "📏"),
                Word("short", "ʃɔːrt", "низкий/короткий", "📐"),
                Word("fast", "fæst", "быстрый", "🏎️"),
                Word("slow", "sloʊ", "медленный", "🐌"),
                Word("strong", "strɒŋ", "сильный", "💪"),
                Word("weak", "wiːk", "слабый", "🥀"),
                Word("heavy", "ˈhevi", "тяжёлый", "🏋🏻"),
                Word("light", "laɪt", "лёгкий", "🪶"),
                Word("expensive", "ɪkˈspensɪv", "дорогой", "💎"),
                Word("cheap", "tʃiːp", "дешёвый", "🪙"),
                Word("easy", "ˈiːzi", "лёгкий (простой)", "✅"),
                Word("difficult", "ˈdɪfɪkəlt", "трудный", "❌"),
                Word("clean", "kliːn", "чистый", "✨"),
                Word("dirty", "ˈdɜːrti", "грязный", "💩"),
                Word("new", "njuː", "новый", "🆕"),
                Word("old", "oʊld", "старый", "👴🏻"),
                Word("wide", "waɪd", "широкий", "↔️"),
                Word("narrow", "ˈnæroʊ", "узкий", "🔀")
            )
        ),
        Category(
            id = "time",
            title = "Время",
            icon = "⏰",
            words = listOf(
                Word("morning", "ˈmɔːrnɪŋ", "утро", "🌅"),
                Word("afternoon", "ˌæftərˈnuːn", "день", "🌞"),
                Word("evening", "ˈiːvnɪŋ", "вечер", "🌇"),
                Word("night", "naɪt", "ночь", "🌙"),
                Word("today", "təˈdeɪ", "сегодня", "📅"),
                Word("tomorrow", "təˈmɒroʊ", "завтра", "➡️"),
                Word("yesterday", "ˈjestərdeɪ", "вчера", "⬅️"),
                Word("week", "wiːk", "неделя", "🗓️"),
                Word("month", "mʌnθ", "месяц", "📆"),
                Word("year", "jɪr", "год", "📅"),
                Word("hour", "ˈaʊər", "час", "⏰"),
                Word("minute", "ˈmɪnɪt", "минута", "⏱️"),
                Word("second", "ˈsekənd", "секунда", "⏲️"),
                Word("clock", "klɒk", "часы", "🕐"),
                Word("early", "ˈɜːrli", "рано", "⏪"),
                Word("late", "leɪt", "поздно", "⏰"),
                Word("weekend", "ˈwiːkend", "выходные", "🎉"),
                Word("midnight", "ˈmɪdnaɪt", "полночь", "🌃"),
                Word("noon", "nuːn", "полдень", "🌞"),
                Word("century", "ˈsentʃəri", "век", "💯")
            )
        )
    )
}
