package com.english.pronunciation

/**
 * First batch of thematic word blocks. More categories will be added
 * incrementally to reach the full planned set.
 */
object CategoryBank {
    val categories = listOf(
        Category(
            id = "tricky_sounds",
            title = "Сложные звуки",
            icon = "🗣️",
            words = listOf(
                Word("apple", "ˈæp.əl", "яблоко", "🍎"),
                Word("water", "ˈwɔː.tər", "вода", "💧"),
                Word("squirrel", "ˈskwɪr.əl", "белка", "🐿️"),
                Word("thumb", "θʌm", "большой палец", "👍"),
                Word("this", "ðɪs", "это", "👉"),
                Word("world", "wɜːld", "мир", "🌍"),
                Word("clothes", "kloʊðz", "одежда", "👕"),
                Word("vegetable", "ˈvedʒ.tə.bəl", "овощ", "🥦"),
                Word("weather", "ˈweð.ər", "погода", "🌦️"),
                Word("wolf", "wʊlf", "волк", "🐺"),
                Word("hello", "həˈloʊ", "привет", "👋"),
                Word("comfortable", "ˈkʌmf.tə.bəl", "удобный", "🛋️"),
                Word("chocolate", "ˈtʃɒk.lət", "шоколад", "🍫"),
                Word("island", "ˈaɪ.lənd", "остров", "🏝️"),
                Word("beautiful", "ˈbjuː.tɪ.fəl", "красивый", "🌸"),
                Word("mountain", "ˈmaʊn.tən", "гора", "⛰️"),
                Word("umbrella", "ʌmˈbrel.ə", "зонт", "☂️"),
                Word("bird", "bɜːd", "птица", "🐦"),
                Word("bridge", "brɪdʒ", "мост", "🌉"),
                Word("rabbit", "ˈræb.ɪt", "кролик", "🐰")
            )
        ),
        Category(
            id = "city",
            title = "Город",
            icon = "🏙️",
            words = listOf(
                Word("street", "striːt", "улица", "🛣️"),
                Word("building", "ˈbɪldɪŋ", "здание", "🏢"),
                Word("bridge", "brɪdʒ", "мост", "🌉"),
                Word("park", "pɑːrk", "парк", "🏞️"),
                Word("shop", "ʃɒp", "магазин", "🏪"),
                Word("bus", "bʌs", "автобус", "🚌"),
                Word("train", "treɪn", "поезд", "🚆"),
                Word("traffic light", "ˈtræfɪk laɪt", "светофор", "🚦"),
                Word("bank", "bæŋk", "банк", "🏦"),
                Word("church", "tʃɜːrtʃ", "церковь", "⛪"),
                Word("restaurant", "ˈrestərɒnt", "ресторан", "🍽️"),
                Word("hotel", "hoʊˈtel", "отель", "🏨"),
                Word("museum", "mjuˈziːəm", "музей", "🏛️"),
                Word("library", "ˈlaɪbreri", "библиотека", "📚"),
                Word("hospital", "ˈhɒspɪtl", "больница", "🏥"),
                Word("school", "skuːl", "школа", "🏫"),
                Word("station", "ˈsteɪʃn", "вокзал", "🚉"),
                Word("square", "skwer", "площадь", "🏙️"),
                Word("tower", "ˈtaʊər", "башня", "🗼"),
                Word("city", "ˈsɪti", "город", "🌆")
            )
        ),
        Category(
            id = "family",
            title = "Семья",
            icon = "👨‍👩‍👧‍👦",
            words = listOf(
                Word("mother", "ˈmʌðər", "мама", "👩"),
                Word("father", "ˈfɑːðər", "папа", "👨"),
                Word("sister", "ˈsɪstər", "сестра", "👧"),
                Word("brother", "ˈbrʌðər", "брат", "👦"),
                Word("grandmother", "ˈɡrænmʌðər", "бабушка", "👵"),
                Word("grandfather", "ˈɡrænfɑːðər", "дедушка", "👴"),
                Word("daughter", "ˈdɔːtər", "дочь", "👧"),
                Word("son", "sʌn", "сын", "👦"),
                Word("aunt", "ænt", "тётя", "👩"),
                Word("uncle", "ˈʌŋkl", "дядя", "👨"),
                Word("cousin", "ˈkʌzn", "двоюродный брат/сестра", "🧑"),
                Word("wife", "waɪf", "жена", "👰"),
                Word("husband", "ˈhʌzbənd", "муж", "🤵"),
                Word("baby", "ˈbeɪbi", "младенец", "👶"),
                Word("parents", "ˈperənts", "родители", "👨‍👩‍👧"),
                Word("family", "ˈfæməli", "семья", "👨‍👩‍👧‍👦"),
                Word("friend", "frend", "друг", "🧑‍🤝‍🧑"),
                Word("neighbor", "ˈneɪbər", "сосед", "🏠"),
                Word("twins", "twɪnz", "близнецы", "👯"),
                Word("relative", "ˈrelətɪv", "родственник", "🧑‍🦰")
            )
        ),
        Category(
            id = "food",
            title = "Еда",
            icon = "🍽️",
            words = listOf(
                Word("bread", "bred", "хлеб", "🍞"),
                Word("cheese", "tʃiːz", "сыр", "🧀"),
                Word("meat", "miːt", "мясо", "🥩"),
                Word("soup", "suːp", "суп", "🍲"),
                Word("salad", "ˈsæləd", "салат", "🥗"),
                Word("sandwich", "ˈsænwɪdʒ", "бутерброд", "🥪"),
                Word("pizza", "ˈpiːtsə", "пицца", "🍕"),
                Word("rice", "raɪs", "рис", "🍚"),
                Word("pasta", "ˈpɑːstə", "паста", "🍝"),
                Word("egg", "eɡ", "яйцо", "🥚"),
                Word("butter", "ˈbʌtər", "масло", "🧈"),
                Word("honey", "ˈhʌni", "мёд", "🍯"),
                Word("sugar", "ˈʃʊɡər", "сахар", "🍬"),
                Word("salt", "sɔːlt", "соль", "🧂"),
                Word("pepper", "ˈpepər", "перец", "🫑"),
                Word("sauce", "sɔːs", "соус", "🥫"),
                Word("cake", "keɪk", "торт", "🎂"),
                Word("cookie", "ˈkʊki", "печенье", "🍪"),
                Word("breakfast", "ˈbrekfəst", "завтрак", "🍳"),
                Word("dinner", "ˈdɪnər", "ужин", "🍽️")
            )
        ),
        Category(
            id = "animals",
            title = "Животные",
            icon = "🐾",
            words = listOf(
                Word("dog", "dɒɡ", "собака", "🐶"),
                Word("cat", "kæt", "кошка", "🐱"),
                Word("horse", "hɔːrs", "лошадь", "🐴"),
                Word("cow", "kaʊ", "корова", "🐄"),
                Word("sheep", "ʃiːp", "овца", "🐑"),
                Word("pig", "pɪɡ", "свинья", "🐷"),
                Word("chicken", "ˈtʃɪkɪn", "курица", "🐔"),
                Word("duck", "dʌk", "утка", "🦆"),
                Word("fish", "fɪʃ", "рыба", "🐟"),
                Word("lion", "ˈlaɪən", "лев", "🦁"),
                Word("tiger", "ˈtaɪɡər", "тигр", "🐯"),
                Word("elephant", "ˈelɪfənt", "слон", "🐘"),
                Word("monkey", "ˈmʌŋki", "обезьяна", "🐒"),
                Word("bear", "ber", "медведь", "🐻"),
                Word("fox", "fɒks", "лиса", "🦊"),
                Word("deer", "dɪr", "олень", "🦌"),
                Word("mouse", "maʊs", "мышь", "🐭"),
                Word("frog", "frɒɡ", "лягушка", "🐸"),
                Word("snake", "sneɪk", "змея", "🐍"),
                Word("turtle", "ˈtɜːrtl", "черепаха", "🐢")
            )
        ),
        Category(
            id = "body",
            title = "Тело человека",
            icon = "🧍",
            words = listOf(
                Word("head", "hed", "голова", "🙂"),
                Word("hand", "hænd", "рука (кисть)", "✋"),
                Word("leg", "leɡ", "нога", "🦵"),
                Word("arm", "ɑːrm", "рука", "🦾"),
                Word("eye", "aɪ", "глаз", "👁️"),
                Word("ear", "ɪr", "ухо", "👂"),
                Word("nose", "noʊz", "нос", "👃"),
                Word("mouth", "maʊθ", "рот", "👄"),
                Word("hair", "her", "волосы", "💇"),
                Word("tooth", "tuːθ", "зуб", "🦷"),
                Word("finger", "ˈfɪŋɡər", "палец", "👆"),
                Word("neck", "nek", "шея", "🦒"),
                Word("shoulder", "ˈʃoʊldər", "плечо", "🤷"),
                Word("back", "bæk", "спина", "🧍"),
                Word("knee", "niː", "колено", "🦵"),
                Word("foot", "fʊt", "ступня", "🦶"),
                Word("chest", "tʃest", "грудь", "🫁"),
                Word("heart", "hɑːrt", "сердце", "❤️"),
                Word("skin", "skɪn", "кожа", "🧴"),
                Word("elbow", "ˈelboʊ", "локоть", "💪")
            )
        ),
        Category(
            id = "clothes",
            title = "Одежда",
            icon = "👕",
            words = listOf(
                Word("shirt", "ʃɜːrt", "рубашка", "👕"),
                Word("dress", "dres", "платье", "👗"),
                Word("skirt", "skɜːrt", "юбка", "👗"),
                Word("jacket", "ˈdʒækɪt", "куртка", "🧥"),
                Word("coat", "koʊt", "пальто", "🧥"),
                Word("shoes", "ʃuːz", "туфли", "👞"),
                Word("socks", "sɒks", "носки", "🧦"),
                Word("hat", "hæt", "шляпа", "🎩"),
                Word("gloves", "ɡlʌvz", "перчатки", "🧤"),
                Word("scarf", "skɑːrf", "шарф", "🧣"),
                Word("jeans", "dʒiːnz", "джинсы", "👖"),
                Word("sweater", "ˈswetər", "свитер", "🧶"),
                Word("belt", "belt", "ремень", "➰"),
                Word("tie", "taɪ", "галстук", "👔"),
                Word("boots", "buːts", "ботинки", "🥾"),
                Word("pajamas", "pəˈdʒɑːməz", "пижама", "🛌"),
                Word("suit", "suːt", "костюм", "🤵"),
                Word("shorts", "ʃɔːrts", "шорты", "🩳"),
                Word("underwear", "ˈʌndərwer", "нижнее бельё", "🩲"),
                Word("uniform", "ˈjuːnɪfɔːrm", "форма", "🎽")
            )
        ),
        Category(
            id = "house",
            title = "Дом",
            icon = "🏠",
            words = listOf(
                Word("kitchen", "ˈkɪtʃɪn", "кухня", "🍳"),
                Word("bedroom", "ˈbedruːm", "спальня", "🛏️"),
                Word("bathroom", "ˈbæθruːm", "ванная", "🚿"),
                Word("living room", "ˈlɪvɪŋ ruːm", "гостиная", "🛋️"),
                Word("door", "dɔːr", "дверь", "🚪"),
                Word("window", "ˈwɪndoʊ", "окно", "🪟"),
                Word("roof", "ruːf", "крыша", "🏠"),
                Word("wall", "wɔːl", "стена", "🧱"),
                Word("floor", "flɔːr", "пол", "🪵"),
                Word("ceiling", "ˈsiːlɪŋ", "потолок", "⬜"),
                Word("garden", "ˈɡɑːrdn", "сад", "🌻"),
                Word("garage", "ɡəˈrɑːʒ", "гараж", "🚗"),
                Word("stairs", "sterz", "лестница", "🪜"),
                Word("balcony", "ˈbælkəni", "балкон", "🏢"),
                Word("fence", "fens", "забор", "🚧"),
                Word("chimney", "ˈtʃɪmni", "дымоход", "🏭"),
                Word("key", "kiː", "ключ", "🔑"),
                Word("lamp", "læmp", "лампа", "💡"),
                Word("mirror", "ˈmɪrər", "зеркало", "🪞"),
                Word("carpet", "ˈkɑːrpɪt", "ковёр", "🟥")
            )
        ),
        Category(
            id = "nature",
            title = "Природа",
            icon = "🌳",
            words = listOf(
                Word("tree", "triː", "дерево", "🌳"),
                Word("flower", "ˈflaʊər", "цветок", "🌸"),
                Word("grass", "ɡræs", "трава", "🌱"),
                Word("forest", "ˈfɒrɪst", "лес", "🌲"),
                Word("river", "ˈrɪvər", "река", "🏞️"),
                Word("lake", "leɪk", "озеро", "🏞️"),
                Word("mountain", "ˈmaʊntən", "гора", "⛰️"),
                Word("sea", "siː", "море", "🌊"),
                Word("sky", "skaɪ", "небо", "🌤️"),
                Word("sun", "sʌn", "солнце", "☀️"),
                Word("moon", "muːn", "луна", "🌙"),
                Word("star", "stɑːr", "звезда", "⭐"),
                Word("cloud", "klaʊd", "облако", "☁️"),
                Word("rain", "reɪn", "дождь", "🌧️"),
                Word("snow", "snoʊ", "снег", "❄️"),
                Word("wind", "wɪnd", "ветер", "💨"),
                Word("stone", "stoʊn", "камень", "🪨"),
                Word("sand", "sænd", "песок", "🏖️"),
                Word("ice", "aɪs", "лёд", "🧊"),
                Word("leaf", "liːf", "лист", "🍁")
            )
        ),
        Category(
            id = "transport",
            title = "Транспорт",
            icon = "🚗",
            words = listOf(
                Word("car", "kɑːr", "машина", "🚗"),
                Word("bus", "bʌs", "автобус", "🚌"),
                Word("train", "treɪn", "поезд", "🚆"),
                Word("plane", "pleɪn", "самолёт", "✈️"),
                Word("ship", "ʃɪp", "корабль", "🚢"),
                Word("bicycle", "ˈbaɪsɪkl", "велосипед", "🚲"),
                Word("motorcycle", "ˈmoʊtərsaɪkl", "мотоцикл", "🏍️"),
                Word("taxi", "ˈtæksi", "такси", "🚕"),
                Word("subway", "ˈsʌbweɪ", "метро", "🚇"),
                Word("truck", "trʌk", "грузовик", "🚚"),
                Word("boat", "boʊt", "лодка", "⛵"),
                Word("helicopter", "ˈhelɪkɒptər", "вертолёт", "🚁"),
                Word("tram", "træm", "трамвай", "🚊"),
                Word("scooter", "ˈskuːtər", "самокат", "🛴"),
                Word("wheel", "wiːl", "колесо", "🛞"),
                Word("engine", "ˈendʒɪn", "двигатель", "⚙️"),
                Word("ticket", "ˈtɪkɪt", "билет", "🎫"),
                Word("driver", "ˈdraɪvər", "водитель", "🧑‍✈️"),
                Word("airport", "ˈerpɔːrt", "аэропорт", "🛫"),
                Word("road", "roʊd", "дорога", "🛣️")
            )
        ),
        Category(
            id = "professions",
            title = "Профессии",
            icon = "🧑‍💼",
            words = listOf(
                Word("teacher", "ˈtiːtʃər", "учитель", "🧑‍🏫"),
                Word("doctor", "ˈdɒktər", "врач", "🧑‍⚕️"),
                Word("nurse", "nɜːrs", "медсестра", "👩‍⚕️"),
                Word("engineer", "ˌendʒɪˈnɪr", "инженер", "🧑‍🔧"),
                Word("lawyer", "ˈlɔɪər", "юрист", "👨‍⚖️"),
                Word("police officer", "pəˈliːs ˈɔːfɪsər", "полицейский", "👮"),
                Word("firefighter", "ˈfaɪərfaɪtər", "пожарный", "👨‍🚒"),
                Word("chef", "ʃef", "повар", "👨‍🍳"),
                Word("waiter", "ˈweɪtər", "официант", "🧑‍🍽️"),
                Word("pilot", "ˈpaɪlət", "пилот", "👨‍✈️"),
                Word("farmer", "ˈfɑːrmər", "фермер", "👨‍🌾"),
                Word("artist", "ˈɑːrtɪst", "художник", "🎨"),
                Word("musician", "mjuˈzɪʃn", "музыкант", "🎸"),
                Word("actor", "ˈæktər", "актёр", "🎭"),
                Word("scientist", "ˈsaɪəntɪst", "учёный", "🧑‍🔬"),
                Word("dentist", "ˈdentɪst", "стоматолог", "🦷"),
                Word("plumber", "ˈplʌmər", "сантехник", "🔧"),
                Word("electrician", "ɪˌlekˈtrɪʃn", "электрик", "⚡"),
                Word("journalist", "ˈdʒɜːrnəlɪst", "журналист", "📰"),
                Word("hairdresser", "ˈherdresər", "парикмахер", "💇")
            )
        ),
        Category(
            id = "colors",
            title = "Цвета",
            icon = "🎨",
            words = listOf(
                Word("red", "red", "красный", "🔴"),
                Word("blue", "bluː", "синий", "🔵"),
                Word("green", "ɡriːn", "зелёный", "🟢"),
                Word("yellow", "ˈjeloʊ", "жёлтый", "🟡"),
                Word("orange", "ˈɔːrɪndʒ", "оранжевый", "🟠"),
                Word("purple", "ˈpɜːrpl", "фиолетовый", "🟣"),
                Word("pink", "pɪŋk", "розовый", "🩷"),
                Word("brown", "braʊn", "коричневый", "🟤"),
                Word("black", "blæk", "чёрный", "⚫"),
                Word("white", "waɪt", "белый", "⚪"),
                Word("gray", "ɡreɪ", "серый", "🩶"),
                Word("gold", "ɡoʊld", "золотой", "🥇"),
                Word("silver", "ˈsɪlvər", "серебряный", "🥈"),
                Word("turquoise", "ˈtɜːrkwɔɪz", "бирюзовый", "💎"),
                Word("beige", "beɪʒ", "бежевый", "🟨"),
                Word("navy", "ˈneɪvi", "тёмно-синий", "🔷"),
                Word("violet", "ˈvaɪələt", "фиалковый", "🟪"),
                Word("maroon", "məˈruːn", "тёмно-бордовый", "🟥"),
                Word("cyan", "ˈsaɪæn", "голубой", "🩵"),
                Word("lime", "laɪm", "лаймовый", "🟩")
            )
        ),
        Category(
            id = "numbers",
            title = "Числа",
            icon = "🔢",
            words = listOf(
                Word("one", "wʌn", "один", "1️⃣"),
                Word("two", "tuː", "два", "2️⃣"),
                Word("three", "θriː", "три", "3️⃣"),
                Word("four", "fɔːr", "четыре", "4️⃣"),
                Word("five", "faɪv", "пять", "5️⃣"),
                Word("six", "sɪks", "шесть", "6️⃣"),
                Word("seven", "ˈsevn", "семь", "7️⃣"),
                Word("eight", "eɪt", "восемь", "8️⃣"),
                Word("nine", "naɪn", "девять", "9️⃣"),
                Word("ten", "ten", "десять", "🔟"),
                Word("eleven", "ɪˈlevn", "одиннадцать", "🔢"),
                Word("twelve", "twelv", "двенадцать", "🔢"),
                Word("thirteen", "θɜːrˈtiːn", "тринадцать", "🔢"),
                Word("fourteen", "ˌfɔːrˈtiːn", "четырнадцать", "🔢"),
                Word("fifteen", "ˌfɪfˈtiːn", "пятнадцать", "🔢"),
                Word("sixteen", "ˌsɪksˈtiːn", "шестнадцать", "🔢"),
                Word("seventeen", "ˌsevnˈtiːn", "семнадцать", "🔢"),
                Word("eighteen", "ˌeɪˈtiːn", "восемнадцать", "🔢"),
                Word("nineteen", "ˌnaɪnˈtiːn", "девятнадцать", "🔢"),
                Word("twenty", "ˈtwenti", "двадцать", "🔢")
            )
        ),
        Category(
            id = "emotions",
            title = "Эмоции",
            icon = "😊",
            words = listOf(
                Word("happy", "ˈhæpi", "счастливый", "😊"),
                Word("sad", "sæd", "грустный", "😢"),
                Word("angry", "ˈæŋɡri", "злой", "😠"),
                Word("scared", "skerd", "испуганный", "😨"),
                Word("surprised", "sərˈpraɪzd", "удивлённый", "😲"),
                Word("tired", "ˈtaɪərd", "уставший", "😴"),
                Word("excited", "ɪkˈsaɪtɪd", "взволнованный", "🤩"),
                Word("nervous", "ˈnɜːrvəs", "нервный", "😬"),
                Word("proud", "praʊd", "гордый", "😌"),
                Word("bored", "bɔːrd", "скучающий", "😑"),
                Word("confused", "kənˈfjuːzd", "растерянный", "😕"),
                Word("calm", "kɑːm", "спокойный", "🧘"),
                Word("worried", "ˈwɜːrid", "обеспокоенный", "😟"),
                Word("embarrassed", "ɪmˈbærəst", "смущённый", "😳"),
                Word("jealous", "ˈdʒeləs", "ревнивый", "😒"),
                Word("grateful", "ˈɡreɪtfl", "благодарный", "🙏"),
                Word("curious", "ˈkjʊriəs", "любопытный", "🤔"),
                Word("lonely", "ˈloʊnli", "одинокий", "😔"),
                Word("confident", "ˈkɒnfɪdənt", "уверенный", "😎"),
                Word("disappointed", "ˌdɪsəˈpɔɪntɪd", "разочарованный", "😞")
            )
        ),
        Category(
            id = "sport",
            title = "Спорт",
            icon = "⚽",
            words = listOf(
                Word("football", "ˈfʊtbɔːl", "футбол", "⚽"),
                Word("basketball", "ˈbæskɪtbɔːl", "баскетбол", "🏀"),
                Word("tennis", "ˈtenɪs", "теннис", "🎾"),
                Word("swimming", "ˈswɪmɪŋ", "плавание", "🏊"),
                Word("running", "ˈrʌnɪŋ", "бег", "🏃"),
                Word("cycling", "ˈsaɪklɪŋ", "велоспорт", "🚴"),
                Word("boxing", "ˈbɒksɪŋ", "бокс", "🥊"),
                Word("volleyball", "ˈvɒlibɔːl", "волейбол", "🏐"),
                Word("golf", "ɡɒlf", "гольф", "⛳"),
                Word("skiing", "ˈskiːɪŋ", "лыжи", "⛷️"),
                Word("skating", "ˈskeɪtɪŋ", "катание на коньках", "⛸️"),
                Word("gymnastics", "dʒɪmˈnæstɪks", "гимнастика", "🤸"),
                Word("baseball", "ˈbeɪsbɔːl", "бейсбол", "⚾"),
                Word("hockey", "ˈhɒki", "хоккей", "🏒"),
                Word("rugby", "ˈrʌɡbi", "регби", "🏉"),
                Word("athlete", "ˈæθliːt", "спортсмен", "🏅"),
                Word("coach", "koʊtʃ", "тренер", "📣"),
                Word("stadium", "ˈsteɪdiəm", "стадион", "🏟️"),
                Word("medal", "ˈmedl", "медаль", "🥇"),
                Word("champion", "ˈtʃæmpiən", "чемпион", "🏆")
            )
        ),
        Category(
            id = "drinks",
            title = "Напитки",
            icon = "🥤",
            words = listOf(
                Word("tea", "tiː", "чай", "🍵"),
                Word("coffee", "ˈkɒfi", "кофе", "☕"),
                Word("juice", "dʒuːs", "сок", "🧃"),
                Word("milk", "mɪlk", "молоко", "🥛"),
                Word("water", "ˈwɔːtər", "вода", "💧"),
                Word("soda", "ˈsoʊdə", "газировка", "🥤"),
                Word("wine", "waɪn", "вино", "🍷"),
                Word("beer", "bɪr", "пиво", "🍺"),
                Word("lemonade", "ˌleməˈneɪd", "лимонад", "🍋"),
                Word("smoothie", "ˈsmuːði", "смузи", "🍹"),
                Word("cocktail", "ˈkɒkteɪl", "коктейль", "🍸"),
                Word("cola", "ˈkoʊlə", "кола", "🧋"),
                Word("cider", "ˈsaɪdər", "сидр", "🍏"),
                Word("champagne", "ʃæmˈpeɪn", "шампанское", "🍾"),
                Word("hot chocolate", "hɒt ˈtʃɒklət", "какао", "🍫"),
                Word("energy drink", "ˈenərdʒi drɪŋk", "энергетик", "⚡"),
                Word("straw", "strɔː", "трубочка", "🥤"),
                Word("cup", "kʌp", "чашка", "☕"),
                Word("bottle", "ˈbɒtl", "бутылка", "🍾"),
                Word("kettle", "ˈketl", "чайник", "🫖")
            )
        ),
        Category(
            id = "furniture",
            title = "Мебель",
            icon = "🛋️",
            words = listOf(
                Word("table", "ˈteɪbl", "стол", "🟫"),
                Word("chair", "tʃer", "стул", "🪑"),
                Word("sofa", "ˈsoʊfə", "диван", "🛋️"),
                Word("bed", "bed", "кровать", "🛏️"),
                Word("wardrobe", "ˈwɔːrdroʊb", "шкаф", "🚪"),
                Word("shelf", "ʃelf", "полка", "📚"),
                Word("desk", "desk", "письменный стол", "🖥️"),
                Word("drawer", "drɔːr", "ящик", "🗄️"),
                Word("cupboard", "ˈkʌbərd", "буфет", "🗄️"),
                Word("bookcase", "ˈbʊkkeɪs", "книжный шкаф", "📚"),
                Word("stool", "stuːl", "табурет", "🪑"),
                Word("bench", "bentʃ", "скамья", "🪑"),
                Word("cabinet", "ˈkæbɪnət", "тумба", "🗄️"),
                Word("mattress", "ˈmætrəs", "матрас", "🛏️"),
                Word("pillow", "ˈpɪloʊ", "подушка", "🛌"),
                Word("blanket", "ˈblæŋkɪt", "одеяло", "🧣"),
                Word("curtain", "ˈkɜːrtn", "штора", "🪟"),
                Word("rug", "rʌɡ", "коврик", "🟥"),
                Word("armchair", "ˈɑːrmtʃer", "кресло", "🛋️"),
                Word("nightstand", "ˈnaɪtstænd", "тумбочка", "🕯️")
            )
        ),
        Category(
            id = "electronics",
            title = "Электроника",
            icon = "📱",
            words = listOf(
                Word("phone", "foʊn", "телефон", "📱"),
                Word("computer", "kəmˈpjuːtər", "компьютер", "🖥️"),
                Word("laptop", "ˈlæptɒp", "ноутбук", "💻"),
                Word("tablet", "ˈtæblət", "планшет", "📱"),
                Word("television", "ˈtelɪvɪʒn", "телевизор", "📺"),
                Word("camera", "ˈkæmərə", "фотоаппарат", "📷"),
                Word("headphones", "ˈhedfoʊnz", "наушники", "🎧"),
                Word("charger", "ˈtʃɑːrdʒər", "зарядка", "🔌"),
                Word("battery", "ˈbætəri", "батарейка", "🔋"),
                Word("keyboard", "ˈkiːbɔːrd", "клавиатура", "⌨️"),
                Word("mouse", "maʊs", "мышь (компьютерная)", "🖱️"),
                Word("monitor", "ˈmɒnɪtər", "монитор", "🖥️"),
                Word("printer", "ˈprɪntər", "принтер", "🖨️"),
                Word("router", "ˈruːtər", "роутер", "📡"),
                Word("speaker", "ˈspiːkər", "колонка", "🔊"),
                Word("microphone", "ˈmaɪkrəfoʊn", "микрофон", "🎤"),
                Word("remote control", "rɪˈmoʊt kənˈtroʊl", "пульт", "🎛️"),
                Word("console", "ˈkɒnsoʊl", "игровая консоль", "🎮"),
                Word("smartwatch", "ˈsmɑːrtwɒtʃ", "умные часы", "⌚"),
                Word("flash drive", "flæʃ draɪv", "флешка", "💾")
            )
        ),
        Category(
            id = "school",
            title = "Школа",
            icon = "🏫",
            words = listOf(
                Word("student", "ˈstuːdnt", "ученик", "🎓"),
                Word("classroom", "ˈklæsruːm", "класс", "🏫"),
                Word("book", "bʊk", "книга", "📖"),
                Word("pen", "pen", "ручка", "🖊️"),
                Word("pencil", "ˈpensl", "карандаш", "✏️"),
                Word("notebook", "ˈnoʊtbʊk", "тетрадь", "📓"),
                Word("backpack", "ˈbækpæk", "рюкзак", "🎒"),
                Word("blackboard", "ˈblækbɔːrd", "доска", "⬛"),
                Word("eraser", "ɪˈreɪsər", "ластик", "🧼"),
                Word("ruler", "ˈruːlər", "линейка", "📏"),
                Word("homework", "ˈhoʊmwɜːrk", "домашнее задание", "📝"),
                Word("exam", "ɪɡˈzæm", "экзамен", "📝"),
                Word("lesson", "ˈlesn", "урок", "📖"),
                Word("grade", "ɡreɪd", "оценка", "🅰️"),
                Word("calculator", "ˈkælkjəleɪtər", "калькулятор", "🧮"),
                Word("textbook", "ˈtekstbʊk", "учебник", "📕"),
                Word("schedule", "ˈskedʒuːl", "расписание", "🗓️"),
                Word("chalk", "tʃɔːk", "мел", "🖍️"),
                Word("principal", "ˈprɪnsəpl", "директор школы", "🧑‍💼"),
                Word("recess", "ˈriːses", "перемена", "🔔")
            )
        ),
        Category(
            id = "shopping",
            title = "Магазин",
            icon = "🛒",
            words = listOf(
                Word("store", "stɔːr", "магазин", "🏬"),
                Word("cashier", "kæˈʃɪr", "кассир", "🧑‍💼"),
                Word("price", "praɪs", "цена", "🏷️"),
                Word("discount", "ˈdɪskaʊnt", "скидка", "💸"),
                Word("receipt", "rɪˈsiːt", "чек", "🧾"),
                Word("basket", "ˈbæskɪt", "корзина", "🧺"),
                Word("cart", "kɑːrt", "тележка", "🛒"),
                Word("customer", "ˈkʌstəmər", "покупатель", "🙋"),
                Word("wallet", "ˈwɒlɪt", "кошелёк", "👛"),
                Word("credit card", "ˈkredɪt kɑːrd", "банковская карта", "💳"),
                Word("cash", "kæʃ", "наличные", "💵"),
                Word("sale", "seɪl", "распродажа", "🏷️"),
                Word("queue", "kjuː", "очередь", "🚶"),
                Word("bag", "bæɡ", "сумка", "👜"),
                Word("size", "saɪz", "размер", "📏"),
                Word("fitting room", "ˈfɪtɪŋ ruːm", "примерочная", "🚪"),
                Word("brand", "brænd", "бренд", "™️"),
                Word("label", "ˈleɪbl", "этикетка", "🏷️"),
                Word("refund", "ˈriːfʌnd", "возврат денег", "💰"),
                Word("coupon", "ˈkuːpɒn", "купон", "🎟️")
            )
        )
    )
}
