package com.english.pronunciation

/**
 * First batch of thematic word blocks. More categories will be added
 * incrementally to reach the full planned set.
 */
object CategoryBank {
    val categories = listOf(
        Category(
            id = "tricky_sounds",
            title = "Сложные звуки",
            icon = "🗣️",
            words = listOf(
                Word("apple", "ˈæp.əl", "яблоко", "🍎"),
                Word("water", "ˈwɔː.tər", "вода", "💧"),
                Word("squirrel", "ˈskwɪr.əl", "белка", "🐿️"),
                Word("thumb", "θʌm", "большой палец", "👍"),
                Word("this", "ðɪs", "это", "👉"),
                Word("world", "wɜːld", "мир", "🌍"),
                Word("clothes", "kloʊðz", "одежда", "👕"),
                Word("vegetable", "ˈvedʒ.tə.bəl", "овощ", "🥦"),
                Word("weather", "ˈweð.ər", "погода", "🌦️"),
                Word("wolf", "wʊlf", "волк", "🐺"),
                Word("hello", "həˈloʊ", "привет", "👋"),
                Word("comfortable", "ˈkʌmf.tə.bəl", "удобный", "🛋️"),
                Word("chocolate", "ˈtʃɒk.lət", "шоколад", "🍫"),
                Word("island", "ˈaɪ.lənd", "остров", "🏝️"),
                Word("beautiful", "ˈbjuː.tɪ.fəl", "красивый", "🌸"),
                Word("mountain", "ˈmaʊn.tən", "гора", "⛰️"),
                Word("umbrella", "ʌmˈbrel.ə", "зонт", "☂️"),
                Word("bird", "bɜːd", "птица", "🐦"),
                Word("bridge", "brɪdʒ", "мост", "🌉"),
                Word("rabbit", "ˈræb.ɪt", "кролик", "🐰")
            )
        ),
        Category(
            id = "city",
            title = "Город",
            icon = "🏙️",
            words = listOf(
                Word("street", "striːt", "улица", "🛣️"),
                Word("building", "ˈbɪldɪŋ", "здание", "🏢"),
                Word("bridge", "brɪdʒ", "мост", "🌉"),
                Word("park", "pɑːrk", "парк", "🏞️"),
                Word("shop", "ʃɒp", "магазин", "🏪"),
                Word("bus", "bʌs", "автобус", "🚌"),
                Word("train", "treɪn", "поезд", "🚆"),
                Word("traffic light", "ˈtræfɪk laɪt", "светофор", "🚦"),
                Word("bank", "bæŋk", "банк", "🏦"),
                Word("church", "tʃɜːrtʃ", "церковь", "⛪"),
                Word("restaurant", "ˈrestərɒnt", "ресторан", "🍽️"),
                Word("hotel", "hoʊˈtel", "отель", "🏨"),
                Word("museum", "mjuˈziːəm", "музей", "🏛️"),
                Word("library", "ˈlaɪbreri", "библиотека", "📚"),
                Word("hospital", "ˈhɒspɪtl", "больница", "🏥"),
                Word("school", "skuːl", "школа", "🏫"),
                Word("station", "ˈsteɪʃn", "вокзал", "🚉"),
                Word("square", "skwer", "площадь", "🏙️"),
                Word("tower", "ˈtaʊər", "башня", "🗼"),
                Word("city", "ˈsɪti", "город", "🌆")
            )
        ),
        Category(
            id = "family",
            title = "Семья",
            icon = "👨‍👩‍👧‍👦",
            words = listOf(
                Word("mother", "ˈmʌðər", "мама", "👩"),
                Word("father", "ˈfɑːðər", "папа", "👨"),
                Word("sister", "ˈsɪstər", "сестра", "👧"),
                Word("brother", "ˈbrʌðər", "брат", "👦"),
                Word("grandmother", "ˈɡrænmʌðər", "бабушка", "👵"),
                Word("grandfather", "ˈɡrænfɑːðər", "дедушка", "👴"),
                Word("daughter", "ˈdɔːtər", "дочь", "👧"),
                Word("son", "sʌn", "сын", "👦"),
                Word("aunt", "ænt", "тётя", "👩"),
                Word("uncle", "ˈʌŋkl", "дядя", "👨"),
                Word("cousin", "ˈkʌzn", "двоюродный брат/сестра", "🧑"),
                Word("wife", "waɪf", "жена", "👰"),
                Word("husband", "ˈhʌzbənd", "муж", "🤵"),
                Word("baby", "ˈbeɪbi", "младенец", "👶"),
                Word("parents", "ˈperənts", "родители", "👨‍👩‍👧"),
                Word("family", "ˈfæməli", "семья", "👨‍👩‍👧‍👦"),
                Word("friend", "frend", "друг", "🧑‍🤝‍🧑"),
                Word("neighbor", "ˈneɪbər", "сосед", "🏠"),
                Word("twins", "twɪnz", "близнецы", "👯"),
                Word("relative", "ˈrelətɪv", "родственник", "🧑‍🦰")
            )
        ),
        Category(
            id = "food",
            title = "Еда",
            icon = "🍽️",
            words = listOf(
                Word("bread", "bred", "хлеб", "🍞"),
                Word("cheese", "tʃiːz", "сыр", "🧀"),
                Word("meat", "miːt", "мясо", "🥩"),
                Word("soup", "suːp", "суп", "🍲"),
                Word("salad", "ˈsæləd", "салат", "🥗"),
                Word("sandwich", "ˈsænwɪdʒ", "бутерброд", "🥪"),
                Word("pizza", "ˈpiːtsə", "пицца", "🍕"),
                Word("rice", "raɪs", "рис", "🍚"),
                Word("pasta", "ˈpɑːstə", "паста", "🍝"),
                Word("egg", "eɡ", "яйцо", "🥚"),
                Word("butter", "ˈbʌtər", "масло", "🧈"),
                Word("honey", "ˈhʌni", "мёд", "🍯"),
                Word("sugar", "ˈʃʊɡər", "сахар", "🍬"),
                Word("salt", "sɔːlt", "соль", "🧂"),
                Word("pepper", "ˈpepər", "перец", "🫑"),
                Word("sauce", "sɔːs", "соус", "🥫"),
                Word("cake", "keɪk", "торт", "🎂"),
                Word("cookie", "ˈkʊki", "печенье", "🍪"),
                Word("breakfast", "ˈbrekfəst", "завтрак", "🍳"),
                Word("dinner", "ˈdɪnər", "ужин", "🍽️")
            )
        ),
        Category(
            id = "animals",
            title = "Животные",
            icon = "🐾",
            words = listOf(
                Word("dog", "dɒɡ", "собака", "🐶"),
                Word("cat", "kæt", "кошка", "🐱"),
                Word("horse", "hɔːrs", "лошадь", "🐴"),
                Word("cow", "kaʊ", "корова", "🐄"),
                Word("sheep", "ʃiːp", "овца", "🐑"),
                Word("pig", "pɪɡ", "свинья", "🐷"),
                Word("chicken", "ˈtʃɪkɪn", "курица", "🐔"),
                Word("duck", "dʌk", "утка", "🦆"),
                Word("fish", "fɪʃ", "рыба", "🐟"),
                Word("lion", "ˈlaɪən", "лев", "🦁"),
                Word("tiger", "ˈtaɪɡər", "тигр", "🐯"),
                Word("elephant", "ˈelɪfənt", "слон", "🐘"),
                Word("monkey", "ˈmʌŋki", "обезьяна", "🐒"),
                Word("bear", "ber", "медведь", "🐻"),
                Word("fox", "fɒks", "лиса", "🦊"),
                Word("deer", "dɪr", "олень", "🦌"),
                Word("mouse", "maʊs", "мышь", "🐭"),
                Word("frog", "frɒɡ", "лягушка", "🐸"),
                Word("snake", "sneɪk", "змея", "🐍"),
                Word("turtle", "ˈtɜːrtl", "черепаха", "🐢")
            )
        ),
        Category(
            id = "body",
            title = "Тело человека",
            icon = "🧍",
            words = listOf(
                Word("head", "hed", "голова", "🙂"),
                Word("hand", "hænd", "рука (кисть)", "✋"),
                Word("leg", "leɡ", "нога", "🦵"),
                Word("arm", "ɑːrm", "рука", "🦾"),
                Word("eye", "aɪ", "глаз", "👁️"),
                Word("ear", "ɪr", "ухо", "👂"),
                Word("nose", "noʊz", "нос", "👃"),
                Word("mouth", "maʊθ", "рот", "👄"),
                Word("hair", "her", "волосы", "💇"),
                Word("tooth", "tuːθ", "зуб", "🦷"),
                Word("finger", "ˈfɪŋɡər", "палец", "👆"),
                Word("neck", "nek", "шея", "🦒"),
                Word("shoulder", "ˈʃoʊldər", "плечо", "🤷"),
                Word("back", "bæk", "спина", "🧍"),
                Word("knee", "niː", "колено", "🦵"),
                Word("foot", "fʊt", "ступня", "🦶"),
                Word("chest", "tʃest", "грудь", "🫁"),
                Word("heart", "hɑːrt", "сердце", "❤️"),
                Word("skin", "skɪn", "кожа", "🧴"),
                Word("elbow", "ˈelboʊ", "локоть", "💪")
            )
        ),
        Category(
            id = "clothes",
            title = "Одежда",
            icon = "👕",
            words = listOf(
                Word("shirt", "ʃɜːrt", "рубашка", "👕"),
                Word("dress", "dres", "платье", "👗"),
                Word("skirt", "skɜːrt", "юбка", "👗"),
                Word("jacket", "ˈdʒækɪt", "куртка", "🧥"),
                Word("coat", "koʊt", "пальто", "🧥"),
                Word("shoes", "ʃuːz", "туфли", "👞"),
                Word("socks", "sɒks", "носки", "🧦"),
                Word("hat", "hæt", "шляпа", "🎩"),
                Word("gloves", "ɡlʌvz", "перчатки", "🧤"),
                Word("scarf", "skɑːrf", "шарф", "🧣"),
                Word("jeans", "dʒiːnz", "джинсы", "👖"),
                Word("sweater", "ˈswetər", "свитер", "🧶"),
                Word("belt", "belt", "ремень", "➰"),
                Word("tie", "taɪ", "галстук", "👔"),
                Word("boots", "buːts", "ботинки", "🥾"),
                Word("pajamas", "pəˈdʒɑːməz", "пижама", "🛌"),
                Word("suit", "suːt", "костюм", "🤵"),
                Word("shorts", "ʃɔːrts", "шорты", "🩳"),
                Word("underwear", "ˈʌndərwer", "нижнее бельё", "🩲"),
                Word("uniform", "ˈjuːnɪfɔːrm", "форма", "🎽")
            )
        ),
        Category(
            id = "house",
            title = "Дом",
            icon = "🏠",
            words = listOf(
                Word("kitchen", "ˈkɪtʃɪn", "кухня", "🍳"),
                Word("bedroom", "ˈbedruːm", "спальня", "🛏️"),
                Word("bathroom", "ˈbæθruːm", "ванная", "🚿"),
                Word("living room", "ˈlɪvɪŋ ruːm", "гостиная", "🛋️"),
                Word("door", "dɔːr", "дверь", "🚪"),
                Word("window", "ˈwɪndoʊ", "окно", "🪟"),
                Word("roof", "ruːf", "крыша", "🏠"),
                Word("wall", "wɔːl", "стена", "🧱"),
                Word("floor", "flɔːr", "пол", "🪵"),
                Word("ceiling", "ˈsiːlɪŋ", "потолок", "⬜"),
                Word("garden", "ˈɡɑːrdn", "сад", "🌻"),
                Word("garage", "ɡəˈrɑːʒ", "гараж", "🚗"),
                Word("stairs", "sterz", "лестница", "🪜"),
                Word("balcony", "ˈbælkəni", "балкон", "🏢"),
                Word("fence", "fens", "забор", "🚧"),
                Word("chimney", "ˈtʃɪmni", "дымоход", "🏭"),
                Word("key", "kiː", "ключ", "🔑"),
                Word("lamp", "læmp", "лампа", "💡"),
                Word("mirror", "ˈmɪrər", "зеркало", "🪞"),
                Word("carpet", "ˈkɑːrpɪt", "ковёр", "🟥")
            )
        ),
        Category(
            id = "nature",
            title = "Природа",
            icon = "🌳",
            words = listOf(
                Word("tree", "triː", "дерево", "🌳"),
                Word("flower", "ˈflaʊər", "цветок", "🌸"),
                Word("grass", "ɡræs", "трава", "🌱"),
                Word("forest", "ˈfɒrɪst", "лес", "🌲"),
                Word("river", "ˈrɪvər", "река", "🏞️"),
                Word("lake", "leɪk", "озеро", "🏞️"),
                Word("mountain", "ˈmaʊntən", "гора", "⛰️"),
                Word("sea", "siː", "море", "🌊"),
                Word("sky", "skaɪ", "небо", "🌤️"),
                Word("sun", "sʌn", "солнце", "☀️"),
                Word("moon", "muːn", "луна", "🌙"),
                Word("star", "stɑːr", "звезда", "⭐"),
                Word("cloud", "klaʊd", "облако", "☁️"),
                Word("rain", "reɪn", "дождь", "🌧️"),
                Word("snow", "snoʊ", "снег", "❄️"),
                Word("wind", "wɪnd", "ветер", "💨"),
                Word("stone", "stoʊn", "камень", "🪨"),
                Word("sand", "sænd", "песок", "🏖️"),
                Word("ice", "aɪs", "лёд", "🧊"),
                Word("leaf", "liːf", "лист", "🍁")
            )
        ),
        Category(
            id = "transport",
            title = "Транспорт",
            icon = "🚗",
            words = listOf(
                Word("car", "kɑːr", "машина", "🚗"),
                Word("bus", "bʌs", "автобус", "🚌"),
                Word("train", "treɪn", "поезд", "🚆"),
                Word("plane", "pleɪn", "самолёт", "✈️"),
                Word("ship", "ʃɪp", "корабль", "🚢"),
                Word("bicycle", "ˈbaɪsɪkl", "велосипед", "🚲"),
                Word("motorcycle", "ˈmoʊtərsaɪkl", "мотоцикл", "🏍️"),
                Word("taxi", "ˈtæksi", "такси", "🚕"),
                Word("subway", "ˈsʌbweɪ", "метро", "🚇"),
                Word("truck", "trʌk", "грузовик", "🚚"),
                Word("boat", "boʊt", "лодка", "⛵"),
                Word("helicopter", "ˈhelɪkɒptər", "вертолёт", "🚁"),
                Word("tram", "træm", "трамвай", "🚊"),
                Word("scooter", "ˈskuːtər", "самокат", "🛴"),
                Word("wheel", "wiːl", "колесо", "🛞"),
                Word("engine", "ˈendʒɪn", "двигатель", "⚙️"),
                Word("ticket", "ˈtɪkɪt", "билет", "🎫"),
                Word("driver", "ˈdraɪvər", "водитель", "🧑‍✈️"),
                Word("airport", "ˈerpɔːrt", "аэропорт", "🛫"),
                Word("road", "roʊd", "дорога", "🛣️")
            )
        )
    )
}
