package com.english.pronunciation

import android.content.Context
import android.os.Handler
import android.os.Looper
import android.util.Log
import kotlin.concurrent.thread

/**
 * The two offline dictionaries behind "Мои слова", generated by
 * tools/build_dictionaries.py:
 *
 *  - English → IPA, from the CMU Pronouncing Dictionary;
 *  - English → Russian, inverted from OpenRussian (CC BY-SA 4.0).
 *
 * Both only ever suggest: a word missing here can still be saved.
 */
object Dictionary {

    data class Entry(val transcription: String?, val translations: List<String>) {
        val known: Boolean get() = transcription != null || translations.isNotEmpty()
    }

    private const val TAG = "Dictionary"

    @Volatile
    private var ipa: SortedTable? = null

    @Volatile
    private var ru: SortedTable? = null

    private var loadStarted = false
    private val main = Handler(Looper.getMainLooper())

    val isReady: Boolean get() = ipa != null && ru != null

    /** Loads both files in the background; [onReady] runs on the main thread. */
    fun prepare(context: Context, onReady: () -> Unit) {
        if (isReady || loadStarted) {
            if (isReady) main.post(onReady)
            return
        }
        loadStarted = true
        val assets = context.applicationContext.assets
        thread(name = "dictionary-load") {
            try {
                ipa = SortedTable(assets.open("dict/en_ipa.txt").bufferedReader().use { it.readText() })
                ru = SortedTable(assets.open("dict/en_ru.txt").bufferedReader().use { it.readText() })
            } catch (t: Throwable) {
                Log.e(TAG, "dictionary failed to load", t)
                loadStarted = false
            }
            main.post(onReady)
        }
    }

    /** A phrase is looked up whole first, then word by word for its transcription. */
    fun lookup(word: String): Entry {
        val key = normalise(word)
        if (key.isEmpty()) return Entry(null, emptyList())
        val translations = ru?.get(key)?.split('|')?.filter { it.isNotBlank() }.orEmpty()
        val transcription = ipa?.get(key) ?: key.split(' ').takeIf { it.size > 1 }?.let { parts ->
            val each = parts.map { ipa?.get(it) }
            if (each.all { it != null }) each.joinToString(" ") else null
        }
        return Entry(transcription, translations)
    }

    /**
     * Real words close to a misspelling. Only the Russian dictionary's headwords
     * are searched: they are everyday vocabulary, where the pronunciation list is
     * full of surnames that would make poor suggestions.
     */
    fun suggest(word: String, limit: Int = 3): List<String> {
        val table = ru ?: return emptyList()
        val key = normalise(word)
        if (key.length < 3) return emptyList()
        val maxDistance = if (key.length <= 4) 1 else 2
        val found = ArrayList<Pair<String, Int>>()
        for (i in 0 until table.size) {
            val candidate = table.keyAt(i)
            if (kotlin.math.abs(candidate.length - key.length) > maxDistance) continue
            val d = distance(key, candidate, maxDistance)
            if (d in 1..maxDistance) found += candidate to d
        }
        return found.sortedBy { it.second }.take(limit).map { it.first }
    }

    fun normalise(word: String): String =
        word.trim().lowercase().replace(Regex("\\s+"), " ")

    /** Levenshtein distance, giving up early once it must exceed [limit]. */
    private fun distance(a: String, b: String, limit: Int): Int {
        var previous = IntArray(b.length + 1) { it }
        var current = IntArray(b.length + 1)
        for (i in 1..a.length) {
            current[0] = i
            var rowBest = current[0]
            for (j in 1..b.length) {
                val cost = if (a[i - 1] == b[j - 1]) 0 else 1
                current[j] = minOf(previous[j] + 1, current[j - 1] + 1, previous[j - 1] + cost)
                if (current[j] < rowBest) rowBest = current[j]
            }
            if (rowBest > limit) return limit + 1
            val swap = previous
            previous = current
            current = swap
        }
        return previous[b.length]
    }
}

/**
 * A sorted "key<TAB>value" file kept as one string plus line offsets, so the
 * 125 000-word pronunciation list costs a few megabytes rather than a map of
 * a quarter of a million small strings. Lookups are binary searches.
 */
private class SortedTable(private val text: String) {

    private val starts: IntArray

    init {
        val offsets = ArrayList<Int>(130_000)
        var lineStart = 0
        while (lineStart < text.length) {
            offsets += lineStart
            val end = text.indexOf('\n', lineStart)
            lineStart = if (end < 0) text.length else end + 1
        }
        starts = offsets.toIntArray()
    }

    val size: Int get() = starts.size

    fun keyAt(i: Int): String {
        val start = starts[i]
        return text.substring(start, text.indexOf('\t', start))
    }

    private fun valueAt(i: Int): String {
        val tab = text.indexOf('\t', starts[i])
        val end = text.indexOf('\n', tab).let { if (it < 0) text.length else it }
        return text.substring(tab + 1, end)
    }

    fun get(key: String): String? {
        var low = 0
        var high = starts.size - 1
        while (low <= high) {
            val mid = (low + high) ushr 1
            val cmp = keyAt(mid).compareTo(key)
            when {
                cmp < 0 -> low = mid + 1
                cmp > 0 -> high = mid - 1
                else -> return valueAt(mid)
            }
        }
        return null
    }
}
